export const components = [
  { text: "Foo 组件示例", link: "/components/foo" },
  { text: "Test4 测试4", link: "/components/test4" },
  { text: "Test3 测试3", link: "/components/test3" },
  { text: "Test1 测试1", link: "/components/test1" },
  { text: "Test2 测试2", link: "/components/test2" },
  { text: "Test1 ", link: "/components/test1" },
  { text: "Test5 测试5", link: "/components/test5" },
  { text: "Test6 测试6", link: "/components/test6" },
  { text: "Test9 测试9", link: "/components/test9" },
  { text: "Test10 测试10", link: "/components/test10" },
{ text: 'Test12 测试12', link: '/components/test12' },
 { text: 'Test13 ', link: '/components/test13' },
 { text: 'Test14 测试14', link: '/components/test14' },
 { text: 'Test22 ', link: '/components/test22' },
 { text: 'Test24 测试24', link: '/components/test24' },
]; // end
